export const FETCH_PROFILES = 'FETCH_PROFILES';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR'; 
export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES';
export const EXPERIENCE_ERROR = 'EXPERIENCE_ERROR';